# Generated by Django 3.2.3 on 2021-05-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210524_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='main_app.Tag'),
        ),
    ]
