# Generated by Django 3.2.3 on 2021-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_name_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main_app.Tag'),
        ),
    ]
