# Generated by Django 3.2.3 on 2021-06-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210527_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
