# Generated by Django 3.2.3 on 2021-06-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
